### ISSUE TITLE
git merge upstream/master

### ISSUE THREAD

**Issue by dddodums** [TPRU-India/OG-India#16]
When I do:

**git merge upstream/master**

It gives me the following error:

**error: Your local changes to the following files would be overwritten by merge:
        environment.yml
        ogindia/constants.py
        ogindia/demographics.py
        ogindia/get_micro_data.py
        ogindia/income.py
        ogindia/output_plots.py
        ogindia/parameter_plots.py
        ogindia/parameter_tables.py
        ogindia/txfunc.py
        ogindia/utils.py
        setup.py
Please commit your changes or stash them before you merge.
Aborting
Updating f4237fd..5903eff**

What does this mean? What should I do? Thank you.

Best Regards,

Sana

**Comment by jdebacker** [comment]
Try a “git stash” before the merge.

**Comment by dddodums** [comment]
It still gives me error:

**(base) C:\Users\wb544155\Documents\GitHub\OG-India>git stash
Saved working directory and index state WIP on master: f4237fd Merge pull request #6 from rickecon/latex
error: unable to create file Icon?: Invalid argument
fatal: Could not reset index file to revision 'HEAD'.

(base) C:\Users\wb544155\Documents\GitHub\OG-India>git merge upstream/master
error: Your local changes to the following files would be overwritten by merge:
        environment.yml
        ogindia/constants.py
        ogindia/demographics.py
        ogindia/get_micro_data.py
        ogindia/income.py
        ogindia/output_plots.py
        ogindia/parameter_plots.py
        ogindia/parameter_tables.py
        ogindia/txfunc.py
        ogindia/utils.py
        setup.py
Please commit your changes or stash them before you merge.
Aborting
Updating f4237fd..5903eff**

**Comment by jdebacker** [comment]
@dddodums Has this been resolved for you?
